#[[redirects]]
#  from = "/"
#  to = "/start"
#  force = true

[[redirects]]
  from = "/quiz"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/"
  to = "/start.html"
  force = true
  status = 200
  headers = {X-From = "Netlify"}
